[package]
name = "token_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.5.0"        # ICP Canister Development Kit
ic-cdk-macros = "0.5.0" # Macros for defining canister functions
serde = "1.0"           # Serialization framework
serde_json = "1.0"      # JSON handling

